version: '3'
services:
  filebeat:
    command: filebeat -e -strict.perms=false
    image: docker.elastic.co/beats/filebeat-oss:7.10.2
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/usr/share/filebeat/logs
      - ./certs:/usr/share/filebeat/certs
networks:
  default:
    external:
      name: open-search_opensearch-net