filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
      - /usr/share/filebeat/logs/*.log
output.elasticsearch:
  hosts: ["http://opensearch-node1:9200"]

#filebeat.inputs:
#  - type: log
#    enabled: true
#    paths:
#      - /logs/*.log
#      - /usr/share/filebeat/logs/*.log
#output.kafka:
#  hosts: ["host.docker.internal:29092"]
#  topic: "filebeat"